application: test-cms
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /data/modules/google_appengine/cloud_storage_proxy\.php.*
  script: data/modules/google_appengine/cloud_storage_proxy.php
- url: /([=]*)pages/(modules|modules\_custom)/([/]*)\.php
  script: \1index.php
- url: /([=]*)pg/s/([^\&\?]*)/index\.php
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)/([^\&\?]*)/index\.php(.*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)/index\.php(.*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/index\.php(.*)
  script: \1index.php
- url: /([=]*)pg/index\.php(.*)
  script: \1index.php
- url: /([=]*)pg/s/([^\&\?]*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)/([^\&\?]*)/
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)/([^\&\?]*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)/([^/\&\?]*)
  script: \1index.php
- url: /([=]*)pg/([^/\&\?]*)
  script: \1index.php
- url: /([=]*)pg/s/([^\&\?\.]*)&(.*)
  script: \1index.php
- url: /([=]*)pg/([/\&\?\.]*)/([/\&\?\.]*)/([/\&\?\.]*)&(.*)
  script: \1index.php
- url: /([=]*)pg/([/\&\?\.]*)/([/\&\?\.]*)&(.*)
  script: \1index.php
- url: /([=]*)pg/([/\&\?\.]*)&(.*)
  script: \1index.php
- url: /(site|forum|adminzone|cms|collaboration|docs)/s/([^\&\?]*)\.htm
  script: \1/index.php
- url: /s/([^\&\?]*)\.htm
  script: index\.php
- url: /(site|forum|adminzone|cms|collaboration|docs)/([^/\&\?]+)/([^/\&\?]*)/([^\&\?]*)\.htm
  script: \1/index.php
- url: /(site|forum|adminzone|cms|collaboration|docs)/([^/\&\?]+)/([^/\&\?]*)\.htm
  script: \1/index.php
- url: /(site|forum|adminzone|cms|collaboration|docs)/([^/\&\?]+)\.htm
  script: \1/index.php
- url: /([^/\&\?]+)/([^/\&\?]*)/([^\&\?]*)\.htm
  script: index.php
- url: /([^/\&\?]+)/([^/\&\?]*)\.htm
  script: index.php
- url: /([^/\&\?]+)\.htm
  script: index.php
#- url: /(site|forum|adminzone|cms|collaboration|docs)/s/([^\&\?]*)
#  script: \1/index.php
#- url: /s/([^\&\?]*)
#  script: index\.php
#- url: /(site|forum|adminzone|cms|collaboration|docs)/([^/\&\?]+)/([^/\&\?]*)/([^\&\?]*)
#  script: \1/index.php
#- url: /(site|forum|adminzone|cms|collaboration|docs)/([^/\&\?]+)/([^/\&\?]*)
#  script: \1/index.php
#- url: /(site|forum|adminzone|cms|collaboration|docs)/([^/\&\?]+)
#  script: \1/index.php
#- url: /([^/\&\?]+)/([^/\&\?]*)/([^\&\?]*)
#  script: index.php
#- url: /([^/\&\?]+)/([^/\&\?]*)
#  script: index.php
#- url: /([^/\&\?]+)
#  script: index.php
- url: /(.*\.(css|csv|cur|gif|gz|htm|html|ico|jar|jpg|js|json|mp3|pdf|png|pre|svg|swf|tar|ttf|txt|wav|xml|xsl|zip))
  static_files: \1
  upload: .*\.(css|csv|cur|gif|gz|htm|html|ico|jar|jpg|js|json|mp3|pdf|png|pre|svg|swf|tar|ttf|txt|wav|xml|xsl|zip)
  application_readable: true
- url: /
  script: index.php
- url: /adminzone/
  script: adminzone/index.php
- url: /cms/
  script: cms/index.php
- url: /forum/
  script: forum/index.php
- url: /collaboration/
  script: collaboration/index.php
- url: /test.php
  script: test.php
- url: /docs/
  script: docs/index.php
- url: /_ah/mail/tickets@appid.appspotmail.com
  script: data/incoming_ticket_email.php
  login: admin
- url: /_ah/bounce
  script: data/incoming_bounced_email.php
  login: admin
- url: /(.*\.php)(/.*)?(\?.*)?
  script: \1
#- url: .*
#  script: 404.htm

skip_files:
- ^uploads/(?<!website_specific/).*
- ^caches/.*
- ^data_custom/errorlog.php$
- ^safe_mode_temp/.*
- ^\.git/.*
- ^data_custom/modules/google_appengine/.*
- ^dump.sql
- ^themes/default/templates_cached/.*
- ^themes/admin/templates_cached/.*
- ^_old/.*

inbound_services:
- mail
- mail_bounce

admin_console:
  pages:
  - name: Admin Zone
    url: /adminzone

pagespeed:
  enabled_rewriters:
  - CollapseWhitespace
  - ElideAttributes
  - RemoveComments
  - RemoveQuotes
  - LeftTrimUrls
  disabled_rewriters:
  - ConvertMetaTags
  - InlineCss
  - InlinePreviewImages
  - CombineCss
  - CombineJs
